#
# A desktop-oriented virtual machines management system written in Shell.
#
# Code is available online at https://github.com/magenete/cuckoo
# See LICENSE for licensing information, and README for details.
#
# Copyright (C) 2016 Magenete Systems OÜ.
#


# Variables
cuckoo_os_variables()
{
    CUCKOO_OS_BIN_DIR="${CUCKOO_OS_DIR}bin/"
    CUCKOO_OS_LIB_DIR="${CUCKOO_OS_DIR}lib/"

    CUCKOO_OS_ETC_DIR="${CUCKOO_OS_DIR}etc/"
    CUCKOO_OS_ETC_BACKGROUND_DIR="${CUCKOO_OS_ETC_DIR}background/"
    CUCKOO_OS_ETC_GRUB_DIR="${CUCKOO_OS_ETC_DIR}grub/"
    CUCKOO_OS_ETC_LIGHTDM_DIR="${CUCKOO_OS_ETC_DIR}lightdm/"
    CUCKOO_OS_ETC_XFCE4_DIR="${CUCKOO_OS_ETC_DIR}xfce4/"
    CUCKOO_OS_ETC_XFCE4_THEME_DIR="${CUCKOO_OS_ETC_XFCE4_DIR}theme/"
    CUCKOO_OS_ETC_XFCE4_ICON_DIR="${CUCKOO_OS_ETC_XFCE4_DIR}icon/"
    CUCKOO_OS_ETC_VERSION_FILE="${CUCKOO_OS_ETC_DIR}VERSION"


    CUCKOO_OS_SYSTEM_USER_CUCKOO_OS_DIR="${HOME}/.config/${CUCKOO_OS}/"
    CUCKOO_OS_SYSTEM_USER_AUTOSTART_DIR="${HOME}/.config/autostart/"
    CUCKOO_OS_SYSTEM_USER_AUTOSTART_CUCKOO_OS_SCREEN_SIZE_FILE="${CUCKOO_OS_SYSTEM_USER_AUTOSTART_DIR}${CUCKOO_OS}-screen-size-setup.desktop"
    CUCKOO_OS_SYSTEM_USER_CUCKOO_OS_SCREEN_SIZE_FILE="${CUCKOO_OS_SYSTEM_USER_CUCKOO_OS_DIR}screen-size"
    CUCKOO_OS_SYSTEM_USER_CUCKOO_OS_SCREEN_SIZE_DEFAULT_FILE="${CUCKOO_OS_SYSTEM_USER_CUCKOO_OS_SCREEN_SIZE_FILE}.default"
    CUCKOO_OS_SYSTEM_USER_CUCKOO_OS_SCREEN_SIZE="$(cat "$CUCKOO_OS_SYSTEM_USER_CUCKOO_OS_SCREEN_SIZE_FILE" 2> /dev/null)"
    CUCKOO_OS_SYSTEM_USER_XFCE4_CONF_XML_DIR="${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml/"
    CUCKOO_OS_SYSTEM_USER_XFCE4_CONF_DESKTOP_XML_FILE="${CUCKOO_OS_SYSTEM_USER_XFCE4_CONF_XML_DIR}xfce4-desktop.xml"
    CUCKOO_OS_SYSTEM_USER_XFCE4_CONF_XSETTINGS_XML_FILE="${CUCKOO_OS_SYSTEM_USER_XFCE4_CONF_XML_DIR}xsettings.xml"
    CUCKOO_OS_SYSTEM_USER_XFCE4_CONF_DISPLAYS_XML_FILE="${CUCKOO_OS_SYSTEM_USER_XFCE4_CONF_XML_DIR}displays.xml"


    CUCKOO_OS_SYSTEM_ETC_LIGHTDM_DIR="/etc/lightdm/"
    CUCKOO_OS_SYSTEM_ETC_LIGHTDM_FILE="${CUCKOO_OS_SYSTEM_ETC_LIGHTDM_DIR}lightdm-gtk-greeter.conf"
    CUCKOO_OS_SYSTEM_ETC_LIGHTDM_FILE_DEFAULT="${CUCKOO_OS_SYSTEM_ETC_LIGHTDM_FILE}.default"
    CUCKOO_OS_SYSTEM_ETC_LIGHTDM_FILE_DEFAULT_BACKUP="${CUCKOO_OS_SYSTEM_ETC_LIGHTDM_FILE_DEFAULT}.backup"
    CUCKOO_OS_SYSTEM_ETC_LIGHTDM_CUCKOO_OS_DIR="${CUCKOO_OS_SYSTEM_ETC_LIGHTDM_DIR}${CUCKOO_OS}/"
    CUCKOO_OS_SYSTEM_ETC_LIGHTDM_CUCKOO_OS_SCREEN_SIZE_FILE="${CUCKOO_OS_SYSTEM_ETC_LIGHTDM_CUCKOO_OS_DIR}screen-size"
    CUCKOO_OS_SYSTEM_ETC_LIGHTDM_CUCKOO_OS_SCREEN_SIZE_DEFAULT_FILE="${CUCKOO_OS_SYSTEM_ETC_LIGHTDM_CUCKOO_OS_SCREEN_SIZE_FILE}.default"
    CUCKOO_OS_SYSTEM_ETC_LIGHTDM_CUCKOO_OS_SCREEN_SIZE="$(cat "$CUCKOO_OS_SYSTEM_ETC_LIGHTDM_CUCKOO_OS_SCREEN_SIZE_FILE" 2> /dev/null)"
    CUCKOO_OS_SYSTEM_ETC_LIGHTDM_CUCKOO_OS_GREETER_DIR="${CUCKOO_OS_SYSTEM_ETC_LIGHTDM_CUCKOO_OS_DIR}lightdm-gtk-greeter/"

    CUCKOO_OS_SYSTEM_USR_SHARE_LIGHTDM_DIR="/usr/share/lightdm/"
    CUCKOO_OS_SYSTEM_USR_SHARE_LIGHTDM_CUCKOO_OS_DIR="${CUCKOO_OS_SYSTEM_USR_SHARE_LIGHTDM_DIR}${CUCKOO_OS}/"
    CUCKOO_OS_SYSTEM_USR_SHARE_LIGHTDM_CONF_DIR="${CUCKOO_OS_SYSTEM_USR_SHARE_LIGHTDM_DIR}lightdm.conf.d/"
    CUCKOO_OS_SYSTEM_USR_SHARE_LIGHTDM_CUCKOO_OS_FILE="${CUCKOO_OS_SYSTEM_USR_SHARE_LIGHTDM_CONF_DIR}${CUCKOO_OS}-lightdm.conf"

    CUCKOO_OS_SYSTEM_IMAGES_DIR="/usr/share/images/desktop-base/"
    CUCKOO_OS_SYSTEM_IMAGES_CUCKOO_OS_DIR="${CUCKOO_OS_SYSTEM_IMAGES_DIR}${CUCKOO_OS}/"
    CUCKOO_OS_SYSTEM_IMAGES_CUCKOO_OS_BACKGROUND_DIR="${CUCKOO_OS_SYSTEM_IMAGES_CUCKOO_OS_DIR}background/"

    CUCKOO_OS_SYSTEM_THEMES_DIR="/usr/share/themes/"
    CUCKOO_OS_SYSTEM_ICONS_DIR="/usr/share/icons/"

    CUCKOO_OS_SYSTEM_GRUB_CONFIG_FILE="/boot/grub/grub.cfg"
    CUCKOO_OS_SYSTEM_GRUB_THEME_DIR="/boot/grub/themes/"
    CUCKOO_OS_SYSTEM_GRUB_THEME_CUCKOO_OS_BACKGROUND_DIR="${CUCKOO_OS_SYSTEM_GRUB_THEME_DIR}${CUCKOO_OS}/background/"
}


# Variables check
cuckoo_os_variables_check()
{
    [ ! -z "$CUCKOO_OS_SYSTEM_SCREEN_SIZE" ] && [ -z "$CUCKOO_OS_ACTION" ] && CUCKOO_OS_ACTION="screen-size"
    CUCKOO_OS_ACTION="${CUCKOO_OS_ACTION:=$CUCKOO_OS_ACTION_DEFAULT}"

    CUCKOO_OS_STYLE="${CUCKOO_OS_STYLE:=$CUCKOO_OS_STYLE_DEFAULT}"
    CUCKOO_OS_STYLE_MODE="${CUCKOO_OS_STYLE_MODE:=$CUCKOO_OS_STYLE_MODE_DEFAULT}"

    CUCKOO_OS_STYLE_THEME_FONT_DPI="${CUCKOO_OS_STYLE_THEME_FONT_DPI:=$CUCKOO_OS_STYLE_THEME_FONT_DPI_DEFAULT}"
}
